pipeline {
    agent any

    stages {
        stage('Maven Build & Sonar') {
            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                    args '''
                        -v $HOME/.m2:/root/.m2:z
                        -u root
                        --network devops
                    '''
                    reuseNode true
                }
            }

            stages {
                stage('Analyse Sonar') {
                    steps {
                        dir('biblio-boot') {
                            withSonarQubeEnv('SonarQube') {
                                sh "mvn clean verify sonar:sonar -DskipTests -Dsonar.projectKey=biblio-boot -Dsonar.projectName=biblio-boot"
                            }
                        }
                    }
                }

            }
        }           

        stage('Docker Build') {
            steps {
                dir('biblio-boot') {
                    sh 'docker build -t ajc/biblio:boot .'
                }    
            }
        }

        stage('Docker Deploy') {
            steps {
                dir('./') {
                    sh 'docker compose up -d'
                }
            }
        }
    }
}