# ===== 1) Build image =====
FROM maven:3.9.11-eclipse-temurin-21 AS builder

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY ./src ./src
RUN mvn package -DskipTests

# ===== 2) Runtime image =====
FROM eclipse-temurin:21-jdk

WORKDIR /app

# On copie le mode exécutable Quarkus (fast-jar)
COPY --from=builder /app/target/quarkus-app/ /app/

EXPOSE 8080
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0"

CMD ["java", "-jar", "/app/quarkus-run.jar"]